### ISSUE TITLE
Sensors support?

### ISSUE THREAD

**Issue by nagyrobi** [Cossid/TasmotaDeviceGroupsForESPHome#5]
Is it possible to send sensor states from one ESPHome node to another with this component?

Eg numeric, binary or text sensors. Grab them on the target node with template sensors.

**Comment by Cossid** [comment]
That is not something Tasmota supported as far as I can tell.  Technically, it could be done with a little custom work, but I'm not sure they would/should sync states (sensors are inherently read-only).  Instead, Tasmota had Events and Commands, but those are currently not implemented either.

**Comment by nagyrobi** [comment]
According to [Tasmota doc](https://tasmota.github.io/docs/Device-Groups/),

> A framework to allow multiple devices to be in a group with values such as power, light color, color temperature, brightness, PWM values, _sensor values_ and more, all shared with other devices in the group.

Maybe that's a mistake in their doc?
