### ISSUE TITLE
ESP-IDF?

### ISSUE THREAD

**Issue by nagyrobi** [Cossid/TasmotaDeviceGroupsForESPHome#6]
> Does not currently work with ESP-IDF framework, as it lacks an arduino-compatible upd multicast library. 

But how about just simply broadcast to the entire local network ([send the udp packet](https://esphome.io/cookbook/lambda_magic.html#send-udp-commands) to just 255.255.255.255)? Or maybe to a configurable target node only?

**Comment by Cossid** [comment]
Sending is only half the battle (and the easier half), listening and reading in a loop are the parts that are considerably more work and not present.  Specifically, esp-idf does not have the arduino equivalent of `beginMulticast`  esp-idf support will come eventually, it's just not immediately.  This component works fine on ESP32 with the arduino framework for the time being.

**Comment by nagyrobi** [comment]
> This component works fine on ESP32 with the arduino framework for the time being.

The only real reason for IDF is that beside better performance, there are IDF-only components one wants to use on the same node.

**Comment by Cossid** [comment]
I'm aware of that, but for now they remain unsupported and on the todo list.

**Comment by bkbartk** [comment]
I don't know much about esp development, but would this help supporting the unsupported part?
https://github.com/espressif/esp-idf/blob/master/examples/protocols/sockets/udp_multicast/main/udp_multicast_example_main.c
there is some short description
https://github.com/espressif/esp-idf/tree/master/examples/protocols/sockets/udp_multicast

but I don't know if this would automatically be compatible with esphome
