### ISSUE TITLE
Is this component working?

### ISSUE THREAD

**Issue by mikekornikh** [Cossid/TasmotaDeviceGroupsForESPHome#9]
Hi, I've been trying to get this Tasmota group component to work with no luck. I installed 2 Wemos D1 mini boards with monochromatic led strips (PWM controlled MOSFETs) on opposite sides of a kitchen. I need these lights to mirror each other's other's state.  Could you please take a look at my codes and let  me know if I'm doing something wrong? I really appreciate any help at all. Thank you!

Primary Device Code
https://pastebin.com/UndJFtTC

Secondary Device Code
https://pastebin.com/Vz1cSM7g

**Comment by mikekornikh** [comment]
Sorry, I also forgot to mention that there was just very little info about this that I found searching online.

**Comment by Cossid** [comment]
Yes, this component should currently in a working state.  Your configuration looks correct and should work.  If it's not working you likely have network issues with multicast or udp packets.  Do you have other Tasmota devices using dgr successfully on the same network?

**Comment by mikekornikh** [comment]
oh wow, I'll definitely take a look at my network settings to see what I could do about the udp/multicast. I don't have any other Tasmota or even ESPhome devices here. I installed this for my parents, who don't have Home Assistant, which is what I would normally use to accomplish this

**Comment by fastcolors** [comment]
not working for me either.

got 2 Tasmota Devices perfectly working with DevGroups, would like to move the setup to EspHome, but would love to make link between switches happene even in case of HA malfunction.

**Comment by Cossid** [comment]
The code is actively working just fine.  I have more than a dozen groups currently active between switches and lights.  Without logs, direct examples of what isn't working, or network packet logging, there is not much additional help that can be given.
